"use client";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useQuery } from "@tanstack/react-query";
import axios from "axios";
import { useRouter } from "next/navigation";
import { useSection } from "@/lib/store";
import { AnimatePresence, easeIn, motion } from "framer-motion";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type CategoriesType = {
  id: string;
  name: string;
};

const easing = [0.6, -0.05, 0.01, 0.99];

const fadeInUp = {
  initial: {
    y: 10,
    opacity: 0,
  },
  animate: {
    y: 0,
    opacity: 1,
    transition: {
      duration: 0.3,
      ease: easeIn,
    },
  },
};

export default function CategoriesLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { section } = useSection();
  const route = useRouter();
  const { data: categoryResults, error } = useQuery<CategoriesType[]>({
    queryFn: async () => {
      const { data } = await axios.get("http://localhost:3000/categories");
      return data;
    },
    queryKey: ["categories-query"],
  });


  return (
    <motion.div
      className="p-5 fixed top-16"
      initial={{ y: 10, opacity: 0 }}
      animate={{ y: 0, opacity: 1 }}
      exit={{ y: -10, opacity: 0 }}
      transition={{ duration: 0.5 }}
    >
      <Tabs>
        <TabsList className="w-[300px] mb-3">
          {categoryResults?.map((category) => (
            <TabsTrigger
              key={category.id}
              defaultValue={section}
              className="w-[150px] capitalize"
              value={category.id}
              onClick={() => route.push(`/categories/${category.name}`)}
            >
              {category.name}
            </TabsTrigger>
          ))}
        </TabsList>
        {children}
      </Tabs>
    </motion.div>
  );
}
