"use client";

import Header from "@/components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import SideBar from "@/components/SideBar";
import { ThemeProvider } from "next-themes";
import Providers from "@/components/Providers";
import { AnimatePresence, motion, domAnimation, LazyMotion } from "framer-motion";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AnimatePresence>
        <motion.body
          className={`${inter.className} absolute`}
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{duration : 0.7}}
        >
          <Providers>
            <ThemeProvider enableSystem={true} attribute="class">
              <SideBar />
              <Header />
              <div className="flex pt-16">
                <div className="flex-1">{children}</div>
              </div>
            </ThemeProvider>
          </Providers>
        </motion.body>
      </AnimatePresence>
    </html>
  );
}
